export const QUERIES_DASHBOARD = {
  TRAINING_CHART: 'training-chart',
  TRAINING_TABLE: 'training-table',
  TRAINING_DATA: 'training-data',
  MATCHES_CHART: 'matches-chart',
  MATCHES_TABLE: 'matches-table',
  MATCHES_DATA: 'matches-data',
  LEADER_BOARD: 'leader-board',
  MATCH_UPDATE: 'match-update',
  DIARIES_STATISTIC: 'diaries-statistic',
  DASHBOARD_VISIT: 'dashboard-visit',
  DASHBOARD_VISITOR: 'dashboard-visitor',
  DASHBOARD_FAN: 'dashboard-fan',
  DASHBOARD_FRIEND: 'dashboard-friend',
  WELLNESS_CHART: 'wellness-chart',
  WELLNESS_DATA: 'wellness-data',
  PAIN_DATA: 'pain-data',
  HEALTH_DATA: 'health-data',
  DEVELOPMENT_DATA: 'development-data',
}

export const QUERIES_CONTACTS = {
  CONTACT_TEAM: 'contact-team',
  CONTACT_TEAM_MEMBER: 'contact-team-member',
  CONTACT_TEAM_ADMIN: 'contact-team-admin',
  CONTACT_TEAM_OWNER: 'contact-team-owner',
  CONTACT_GROUP: 'contact-group',
  CONTACT_GROUP_MEMBER: 'contact-group-member',
  CONTACT_GROUP_ADMIN: 'contact-group-admin',
  CONTACT_GROUP_OWNER: 'contact-group-owner',
  CONTACT_FANS: 'contact-fans',
}
