const url = `https://dev.api.zporter.co/biographies/players/head-2-head?limit=10&startAfter=1&sorted=asc&statsTab=Current_Season&startDate=2022-04-18T10%3A04%3A46%2B00%3A00&endDate=2022-05-20T10%3A04%3A46%2B00%3A00&userIdQuery=008a5eab-1837-4121-8975-9ec94159b685`
export const a = {
  bioCompare: {
    userA: {
      userId: 'a78a8f3b-7ecb-4cf1-a9f1-403477ffef7e',
      lastUpdatedDate: '2022-05-18',
      username: 'HigTra080101B',
      firstName: 'Highland',
      lastName: 'Tran',
      faceImageUrl:
        'https://firebasestorage.googleapis.com/v0/b/zporter-dev-media/o/media%2F2022-04-05%2011%3A33%3A25.459457?alt=media&token=973a29ea-d7d7-4c05-a27e-a4631a4f98c2',
      bodyImageUrl:
        'https://firebasestorage.googleapis.com/v0/b/zporter-dev.appspot.com/o/files%2FSimulator%20Screen%20Shot%20-%20iPhone%2011%20Pro%20Max%20-%202022-03-16%20at%2013.55.51.png?alt=media&token=49f8fab1-0e82-4c9a-a310-a70bf8850343',
      starRating: 4.5,
      circleCompleted: 90,
      position: 'RB',
      currentClubIconUrl:
        'https://firebasestorage.googleapis.com/v0/b/zporter-dev-media/o/media%2FVMO.png?alt=media&token=a168a48a-bcc1-4f6b-9a02-72ceab1311b1',
      contractedUntil: '2022/03',
      estMarketValue: 999,
      leftFoot: 4.5,
      rightFoot: 4.5,
      bestFoot: 'TWO_FOOTED',
      height: 221,
      weight: 85,
      countryFlagUrl:
        'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939466/country-flags/SWE.png',
      birthDay: '08/01/01',
      age: 14,
      summary: 'A quick and dedicated player',
      socialLinks: {
        youtube: 'https://www.youtube.com/channel/UCwLxgZHR8oDOzJXtXuSB_bA',
        instagram:
          'https://zporter.atlassian.net/jira/software/projects/ZPOWEB/boards/6',
        twitter: '',
        tiktok: '',
        facebook: '',
        veoHighlites: '',
      },
      topVideoLinks: [
        {
          url: 'https://youtu.be/5IafY9dMiFQ',
          thumbnailUrl: 'https://img.youtube.com/vi/5IafY9dMiFQ/sddefault.jpg',
          source: 'YOUTUBE',
        },
      ],
      playerRadarSkills: {
        pace: 82,
        defending: 89,
        shooting: 91,
        attacking: 90,
        tackling: 86,
        passing: 94,
        heading: 89,
        dribbling: 77,
      },
      radarUpdatedByCoach: {
        attacking: 87,
        dribbling: 88,
        shooting: 83,
        tackling: 86,
        heading: 67,
        defending: 89,
        pace: 84,
        passing: 91,
      },
      specialities: ['skillful', 'quick'],
      isPublic: false,
      userRole: 'PLAYER',
      bioUrl: 'https://dev.web.zporter.co/player/HigTra080101B/highland.tran',
      teamIds: ['dJnMUJNERfk8YhqEFMEw'],
    },
    userB: {
      userId: '008a5eab-1837-4121-8975-9ec94159b685',
      lastUpdatedDate: '2022-03-17',
      username: 'Vmo070101',
      firstName: 'Vmodev',
      lastName: null,
      faceImageUrl:
        'https://firebasestorage.googleapis.com/v0/b/zporter-dev-media/o/media%2F2022-03-17%2016%3A19%3A17.853809?alt=media&token=8fae41e7-9b4c-4315-bcdb-09ca6c2a314d',
      bodyImageUrl: null,
      starRating: 4.5,
      circleCompleted: 50,
      position: 'CM',
      currentClubIconUrl:
        'https://firebasestorage.googleapis.com/v0/b/zporter-dev-media/o/media%2FVMO.png?alt=media&token=a168a48a-bcc1-4f6b-9a02-72ceab1311b1',
      contractedUntil: '2022/03',
      estMarketValue: null,
      leftFoot: 4.5,
      rightFoot: 4.5,
      bestFoot: 'TWO_FOOTED',
      height: 160,
      weight: 60,
      countryFlagUrl:
        'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939466/country-flags/SWE.png',
      birthDay: '07/01/01',
      age: 15,
      summary: null,
      socialLinks: {
        instagram: '',
        tiktok: '',
        twitter: '',
        youtube: '',
        veoHighlites: '',
        facebook: '',
      },
      topVideoLinks: [],
      playerRadarSkills: {
        defending: 92,
        shooting: 91,
        dribbling: 91,
        tackling: 92,
        heading: 92,
        pace: 94,
        passing: 91,
        attacking: 93,
      },
      radarUpdatedByCoach: {
        attacking: 0,
        defending: 0,
        dribbling: 0,
        passing: 0,
        shooting: 0,
        pace: 0,
        tackling: 0,
        heading: 0,
      },
      specialities: [],
      isPublic: true,
      userRole: 'PLAYER',
      bioUrl: 'https://dev.web.zporter.co/player/Vmo070101/vmodev.',
      teamIds: ['trfvLTvbwJHITaO5dFCa'],
    },
  },
  trophiesCompare: {
    userA: {
      serieTrophyCount: 2,
      cupTrophyCount: 0,
      otherTrophyCount: 0,
    },
    userB: {
      serieTrophyCount: 0,
      cupTrophyCount: 0,
      otherTrophyCount: 0,
    },
  },
  awardsCompare: {
    userA: {
      MVP: 0,
      POW: 0,
      SOM: 0,
      POM: 2,
      POY: 0,
      DT: 0,
      GOL: 0,
      GOC: 0,
    },
    userB: {
      MVP: 0,
      POW: 0,
      SOM: 0,
      POM: 0,
      POY: 0,
      DT: 0,
      GOL: 0,
      GOC: 0,
    },
  },
  capsCompare: {
    userA: [
      {
        type: 'REGIONAL',
        teamName: 'U15',
        count: 2,
      },
      {
        type: 'NATIONAL',
        teamName: 'U15',
        count: 1,
      },
      {
        type: 'NATIONAL',
        teamName: 'U21',
        count: 1,
      },
    ],
    userB: [],
  },
  matchesCompare: {
    matches: {
      userA: 100,
      totalUserA: 53,
      userB: 0,
      totalUserB: 0,
    },
    points: {
      userA: 100,
      totalUserA: 103,
      userB: 0,
      totalUserB: 0,
    },
    hours: {
      userA: 100,
      totalUserA: 51,
      userB: 0,
      totalUserB: 0,
    },
    goals: {
      userA: 100,
      totalUserA: 12,
      userB: 0,
      totalUserB: 0,
    },
    assists: {
      userA: 100,
      totalUserA: 12,
      userB: 0,
      totalUserB: 0,
    },
    yel: {
      userA: 50,
      totalUserA: 0,
      userB: 50,
      totalUserB: 0,
    },
    red: {
      userA: 100,
      totalUserA: 1,
      userB: 0,
      totalUserB: 0,
    },
  },
  trainingsCompare: {
    sessions: {
      userA: 100,
      totalUserA: 67,
      userB: 0,
      totalUserB: 0,
    },
    hours: {
      userA: 100,
      totalUserA: 196.5,
      userB: 0,
      totalUserB: 0,
    },
    technical: {
      userA: 100,
      totalUserA: 66,
      userB: 0,
      totalUserB: 0,
    },
    tactics: {
      userA: 100,
      totalUserA: 18,
      userB: 0,
      totalUserB: 0,
    },
    physical: {
      userA: 100,
      totalUserA: 11,
      userB: 0,
      totalUserB: 0,
    },
    mental: {
      userA: 100,
      totalUserA: 5,
      userB: 0,
      totalUserB: 0,
    },
  },
}
