export const Constants : {
  GOOGLE_PLACE_API_KEY : 'AIzaSyCHYCMrx7vUSIKrI4NAy3w-JIInILtJnps',
  LANGUAGE_EN : 'en',
  LANGUAGE_VI : 'vi',
  LANGUAGE_SE : 'se',

  KEY_NOTIFICATION : 'notification',
  KEY_NOTIFICATION_APS : 'aps',
  KEY_NOTIFICATION_ALERT : 'alert',
  KEY_NOTIFICATION_TITLE : 'title',
  KEY_NOTIFICATION_BODY : 'body',
  ANDROID_CHANNEL_ID : '19999',
  ANDROID_CHANNEL_NAME : 'zporter',
  ANDROID_CHANNEL_DESCRIPTION : 'zporter',
  NO_SOUND : 'No_Sound',
  TYPE_PERMISSION_STORAGE : 'gallery',
  TYPE_PERMISSION_CAMERA : 'camera',

  APP_NAME : 'Zporter',
  SPECIALITY : 'SPECIALITY',
  INJURY : 'INJURY',
  PRACTICE : 'PRACTICE',

  VERY_LOW : 'VERY_LOW',
  LOW : 'LOW',
  NORMAL : 'NORMAL',
  HIGH : 'HIGH',
  VERY_HIGH : 'VERY_HIGH',

  VERY_BAD : 'VERY_BAD',
  BAD : 'BAD',
  GOOD : 'GOOD',
  VERY_GOOD : 'VERY_GOOD',

  IMAGE : 'IMAGE',
  CAMERA_IMAGE : 'CAMERA_IMAGE',
  VIDEO : 'VIDEO',
  FILE : 'FILE',

  TRAINING : 'TRAINING',
  MATCH : 'MATCH',
  REST : 'REST',
  NEWS : 'news',
  TEAM_TRAINING : 'TEAM_TRAINING',
  GROUP_TRAINING : 'GROUP_TRAINING',
  CAP : 'CAP',
  PERSONAL_TRAINING : 'PERSONAL_TRAINING',
  REST_DAY : 'REST_DAY',
  DEFAULT : 'Default',
  GOAL : 'GOAL',
  DEFAULT_PLAYER_ROLE : 'CAM',
  DASHBOARD_SCREEN : 'DASHBOARD_SCREEN',
  like : 'like',
  unlike : 'unlike',

  /// Post Type
  RSS_NEWS : 'rss_news',
  DIARIES : 'diaries',
  TRANSFER : 'club_transfer_histories',
  PLAYER_OF_THE_WEEKS : 'player_of_the_weeks',

  HEAD2HEAD : 'Head 2 Head',
  NO_RELATIONSHIP : 'no_relationship',
  REQUESTED : 'requested',
  RESPONSE : 'response',
  ACCEPTED : 'accepted',
  REJECTED : 'rejected',

  FRIENDS : 'friends',
  FANS : 'fans',
  FOLLOWS : 'follows',
  FOLLOW_BACK : 'follow_back',

  TEAM : 'team',
  YOURS : 'yours',
  SAVED : 'saved',
  ONE_POST : 'post',
  PROFILE : 'PROFILE',

  frontBodyImgSize : Size(214, 440),
  backBodyImgSize : Size(214, 440),
  YES : 'YES',
  NO : 'NO',

  /// NOTIFICATION TYPE
  // Settings
  REMIND_DIARY_UPDATE_LOCAL : 'DIARY_UPDATE_LOCAL_REMINDER',
  REMIND_ON_PROFILE : 'REMIND_ON_PROFILE',
  REMIND_ON_DIARY_UPDATE : 'REMIND_ON_DIARY_UPDATE',
  INVITE_UPDATE : 'INVITE_UPDATE',
  FEED_UPDATE : 'FEED_UPDATE',
  TEAM_TRAINING_NOTI : 'TEAM_TRAINING',
  MESSAGE_UPDATE : 'MESSAGE_UPDATE',
  MATCH_NOTI : 'MATCH',

  // Relationship
  FOLLOW : 'FOLLOW',
  FRIEND_REQUEST : 'FRIEND_REQUEST',
  FOLLOW_REQUEST : 'FOLLOW_REQUEST',
  ACCEPTED_FRIEND_REQUEST : 'ACCEPTED_FRIEND_REQUEST',
  ACCEPTED_FOLLOW_REQUEST : 'ACCEPTED_FOLLOW_REQUEST',
  REJECT_FRIEND_REQUEST : 'REJECT_FRIEND_REQUEST',
  REJECT_FOLLOW_REQUEST : 'REJECT_FOLLOW_REQUEST',

  // POST ACTIONS
  LIKE_POST : 'LIKE_POST',
  COMMENT_POST : 'COMMENT_POST',

  // TEAM
  ASK_JOIN_TEAM : 'ASK_JOIN_TEAM',
  INVITE_MEMBER_TEAM : 'INVITE_MEMBER_TEAM',
  ACCEPT_JOIN_TEAM : 'ACCEPT_JOIN_TEAM',
  REJECT_JOIN_TEAM : 'REJECT_JOIN_TEAM',
  LEAVE_TEAM : 'LEAVE_TEAM',
  DELETE_MEMBER_TEAM : 'DELETE_MEMBER_TEAM',
  BLOCK_MEMBER_TEAM : 'BLOCK_MEMBER_TEAM',
  MEMBER_CONFIRM_DELETE_MEMBER_TEAM :
      'MEMBER_CONFIRM_DELETE_MEMBER_TEAM',
  MEMBER_CONFIRM_BLOCK_MEMBER_TEAM :
      'MEMBER_CONFIRM_BLOCK_MEMBER_TEAM',
  ADMIN_CONFIRM_DELETE_MEMBER_TEAM :
      'ADMIN_CONFIRM_DELETE_MEMBER_TEAM',
  ADMIN_CONFIRM_BLOCK_MEMBER_TEAM :
      'ADMIN_CONFIRM_BLOCK_MEMBER_TEAM',

  // GROUP
  INVITE_MEMBER_GROUP : 'INVITE_MEMBER_GROUP',
  ASK_JOIN_GROUP : 'ASK_JOIN_GROUP',

  // MESSAGE NOTIFICATION
  SEND_MESSAGE : 'SEND_MESSAGE',

  // ASK FOR REVIEW
  ASK_FOR_REVIEW_SKILL_UPDATES : 'ASK_FOR_REVIEW_SKILL_UPDATES',
  ASK_FOR_REVIEW_DEVELOPMENT_TALK :
      'ASK_FOR_REVIEW_DEVELOPMENT_TALK',

  ///
  SETTINGS : 'SETTINGS',

  /// Contact
  ASC : 'asc',
  DESC : 'desc',

  ALL : 'All',
  MEMBER : 'MEMBER',
  ADMIN : 'ADMIN',
  OWNER : 'OWNER',
  NOT_A_MEMBER : 'NOT_A_MEMBER',

  /// Message
  ZPORTER_USER : 'Zporter User',
  AVATAR_DEFAULT :
      'https://firebasestorage.googleapis.com/v0/b/zporter-dev-media/o/media%2Fface_image_default.png?alt:media&token:65eb03b0-4021-441d-9a4f-d43b47d72c40',
  SEEN : 'seen',
  DELIVERED : 'delivered',
  ERROR : 'error',
  SENDING : 'sending',
  SENT : 'sent',
  DEVELOPMENT_LINK : 'DEVELOPMENT_LINK',
  SKILL_UPDATE_LINK : 'SKILL_UPDATE_LINK',

  SKILL_UPDATES : 'SKILL_UPDATES',

  ///role
  ROLE_PLAYER : 'PLAYER',
  ROLE_COACH : 'COACH',
}