export const diaries = 'diaries'
export const TRAINING = 'TRAINING'
export const MATCH = 'MATCH'
export const plain_posts = 'plain_posts'
export const shared_biographies = 'shared_biographies'
export const remind_update_diaries = 'remind_update_diaries'
export const club_transfer_histories = 'club_transfer_histories'
export const shared_leaderboard = 'shared_leaderboard'
export const personal_goals = 'personal_goals'
export const player_of_the_weeks = 'player_of_the_weeks'
export const rss_news = 'rss_news'
export const zporter_news = 'zporter_news'
export const ztar_of_the_matches = 'ztar_of_the_matches'

export const LIKE = 'like'
export const UN_LIKE = 'unlike'
