export const diaries = 'diaries'
export const TRAINING = 'TRAINING'
export const MATCH = 'MATCH'
export const plain_posts = 'plain_posts'
export const shared_biographies = 'shared_biographies'
export const remind_update_diaries = 'remind_update_diaries'
